workflows:
  react-native-android:
    name: React Native Android
    environment:
      node: latest
    scripts:
      - npm install
      - npx react-native bundle --platform android --dev false --entry-file main.tsx --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
