name: kend_heyati
description: Kend heyati haqqinda melumat proqrami.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # --- BU HİSSƏNİ ƏLAVƏ ETDİK ---
  # İkonları avtomatik yaratmaq üçün paket
  flutter_launcher_icons: ^0.13.1
  # Açılış ekranını avtomatik yaratmaq üçün paket
  flutter_native_splash: ^2.3.1
  # ------------------------------

# --- BU YENİ BÖLMƏLƏRİ ƏLAVƏ ETDİK ---

# 1. Tətbiq İkonu Ayarları
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "kend.jpg" # GitHub-a yüklədiyin şəkilin adı
  # Android üçün adaptiv ikon rəngi (istəsən dəyişə bilərsən)
  adaptive_icon_background: "#FFFFFF" 

# 2. Açılış Ekranı (Splash Screen) Ayarları
flutter_native_splash:
  color: "#FFFFFF" # Arxa fon rəngi (ağ rəng)
  image: "Green Illustrative Growing Forests Sustaining Life Poster.png
" # Mərkəzdə görünəcək loqo şəkilinin adı
  android: true
  ios: true
  fullscreen: true

# -----------------------------------

flutter:
  uses-material-design: true
